### PR TITLE
Truncate standalone test files instead of removing

### LINKED ISSUE #2777: Opening this crate in vscode on Linux leads to files being changed and an endless build loop
### Summary

To reproduce, download this crate and open it in vscode on Linux with rust-analyzer installed. (I did that since I needed to grep for some things the crate does to research Windows-related issues in my code, and I don't have a Windows machine.) This leads to changes showing up in `git diff`, and rust-analyzer hangs in an endless build loop. I reported this with RA at https://github.com/rust-lang/rust-analyzer/issues/16250 but they are saying there isn't much they can do; the reason is that this crate modifies its own source in a build script which causes a reload which causes a build which modifies the source again ad nauseam.

### Crate manifest

_No response_

### Crate code

_No response_

### PR DESCRIPTION
**Pull request by ChrisDenton**
Attempts to fix #2777 by truncating the test files instead of removing them. This may help avoid an endless loop in rust-analyzer (see also https://github.com/rust-lang/rust-analyzer/issues/16250).

cc @RalfJung would you be able to test if this helps?

### CODE REVIEW

**Comment by RalfJung** [comment]
Yes that does seem to fix the endless loop. :)

**Comment by kennykerr** [comment]
I can't repro that nightly warning, but I fixed it here: https://github.com/microsoft/windows-rs/pull/2775/commits/b5e5000f4b0aa2b029626397d42fe8d91463b997

If you merge master you should be good to go.

**Review by kennykerr — DISMISSED** [review]
Maybe a comment about this being a workaround for rust-analyzer as I'm bound to forget why this is used rather than the simpler `remove_file`. 😊

**Comment by ChrisDenton** [comment]
Thanks for testing! I've added a comment to explain why we're doing this.

File: crates/tests/standalone/build.rs [hunk 1]
```diff
@@ -165,7 +165,14 @@ fn write_no_inner_attr(output: &str, filter: &[&str]) {
 }
 
 fn riddle(output: &str, filter: &[&str], config: &[&str]) {
-    _ = std::fs::remove_file(output);
+    // Rust-analyzer may re-run build scripts whenever a source file is deleted
+    // which causes an endless loop if the file is deleted from a build script.
+    // To workaroud this, we truncate the file instead of deleting it.
+    // See #2777.
```
Comment (kennykerr) [inline crates/tests/standalone/build.rs:171]:
```suggestion
    // See https://github.com/microsoft/windows-rs/issues/2777.
```

Just makes it easier to open the issue in VS Code.

Comment (ChrisDenton) [reply crates/tests/standalone/build.rs]: Good point!

**Review by riverar — DISMISSED** [review]

File: crates/tests/standalone/build.rs [hunk 2]
```diff
@@ -165,7 +165,14 @@ fn write_no_inner_attr(output: &str, filter: &[&str]) {
 }
 
 fn riddle(output: &str, filter: &[&str], config: &[&str]) {
-    _ = std::fs::remove_file(output);
+    // Rust-analyzer may re-run build scripts whenever a source file is deleted
+    // which causes an endless loop if the file is deleted from a build script.
+    // To workaroud this, we truncate the file instead of deleting it.
```
Comment (kennykerr) [inline crates/tests/standalone/build.rs:170]:
```suggestion
    // To workaround this, we truncate the file instead of deleting it.
```

Typo.
