### PR TITLE
Type-specific handle validity checking

### LINKED ISSUE #1630: Bug: FindVolumeHandle::is_invalid() does not check for a value of -1
### Which crate is this about?

windows

### Crate version

0.34.0

### Summary

``FindVolumeHandle::is_invalid()`` only considers the value ``0`` to represent an invalid handle which leads to incorrect branches being followed if a function returns a handle value of ``-1`` as its invalid handle code.

### Toolchain version/configuration

Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\Ian\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc
nightly-2022-01-27-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-msvc (default)

installed targets for active toolchain
--------------------------------------

i686-pc-windows-msvc
x86_64-pc-windows-msvc

active toolchain
----------------

nightly-x86_64-pc-windows-msvc (default)
rustc 1.61.0-nightly (d3ad51b48 2022-02-25)

### Reproducible example

```rust
use windows::Win32::Storage::FileSystem::{FindFirstVolumeW, FindVolumeClose};

fn main() {
    unsafe {
        // will return `-1` due to empty output buffer.
        let handle = FindFirstVolumeW(&mut []);
        if !handle.is_invalid() {
            // heap corruption due to handle being `-1`
            FindVolumeClose(handle);
        }
    }
}
```

### Crate manifest

```toml
[package]
name = "find_volume_bug"
version = "0.1.0"
edition = "2021"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.34.0", features = ["Win32_Storage_FileSystem", "Win32_Foundation"] }
```

### Expected behavior

Body of ``if`` block is goes unentered because the handle is invalid and the program exits gracefully.

### Actual behavior

Body of ``if`` block is gets entered because the ``is_invalid`` fails to catch the value ``-1`` and the program exits due to heap corruption.

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by kennykerr**
The win32 metadata now includes information about what constitutes invalid handle values. This update plumbs this through so that you can accurately check whether a handle returned by some function is invalid. Handles will have an `is_invalid` method if their underlying type is a pointer or have at least one invalid value.

With this information in hand, the `bindgen` crate can now combine this with metadata that indicates whether a particular function set the last error so that the caller should use `GetLastError` on failure. This means that functions that return a handle and provide error information in this way will now be transformed to return `-> Result<HANDLE>` instead of just `-> HANDLE`. This should make error handling more predictable. 

Fixes #1630

### CODE REVIEW

File: crates/libs/bindgen/src/handles.rs [hunk 1]
```diff
@@ -20,26 +20,42 @@ pub fn gen_sys_handle(def: &TypeDef, gen: &Gen) -> TokenStream {
...
     let ident = gen_ident(def.name());
-    let signature = gen_signature(def, gen);
+    let underlying_type = underlying_type(def);
+    let signature = gen_default_type(&underlying_type, gen);
+    let check = if underlying_type.is_pointer() {
+        quote! {
+            impl #ident {
+                pub fn is_null(&self) -> bool {
+                    self.0.is_null()
+                }
```
Comment (kennykerr) [inline crates/libs/bindgen/src/handles.rs:30]: Types like `PSID` will get an `is_null` method instead of `is_invalid` when the underlying type is a pointer rather than an integer.

File: crates/libs/bindgen/src/replacements/mod.rs [hunk 2]
```diff
@@ -1,15 +1,13 @@
...
 mod bstr;
-mod handle;
 mod ntstatus;
 
 pub fn gen(def: &TypeDef) -> Option<TokenStream> {
     match def.type_name() {
         TypeName::BOOL => Some(bool32::gen()),
         TypeName::BSTR => Some(bstr::gen()),
         TypeName::NTSTATUS => Some(ntstatus::gen()),
-        TypeName::HANDLE => Some(handle::gen()),
```
Comment (kennykerr) [inline crates/libs/bindgen/src/replacements/mod.rs:12]: `HANDLE` no longer needs to specialized! 😉

File: crates/libs/bindgen/src/functions.rs [hunk 3]
```diff
@@ -202,28 +202,78 @@ fn gen_win_function(def: &MethodDef, gen: &Gen) -> TokenStream {
...
+                    #[inline]
+                    pub unsafe fn #name<#constraints>(#params) -> ::windows::core::Result<#return_type> {
+                        #[cfg(windows)]
+                        {
+                            #link_attr
+                            extern "system" {
+                                fn #name(#(#abi_params),*) -> #return_type;
+                            }
+                            let result__ = #name(#args);
+                            (!result__.is_invalid()).then(||result__).ok_or_else(::windows::core::Error::from_win32)
```
Comment (kennykerr) [inline crates/libs/bindgen/src/functions.rs:269]: Here we check if the returned handle is valid and call `from_win32` if it is invalid to return an error `Result`.

**Review by riverar — APPROVED** [review]
Nice! Really cool to see all this light up with a sprinkle of metadata 🎉
